using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading;
using System.Threading.Tasks;
using CarSpaManagement.Api.Application.Common;
using CarSpaManagement.Api.Application.DTOs.Audit;
using CarSpaManagement.Api.Application.DTOs.Showrooms;
using CarSpaManagement.Api.Application.Interfaces;
using CarSpaManagement.Api.Application.Services;
using CarSpaManagement.Api.Controllers;
using CarSpaManagement.Api.Domain.Entities;
using CarSpaManagement.Api.Domain.Enums;
using CarSpaManagement.Api.Infrastructure.Database;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Xunit;

namespace CarSpaManagement.Api.Tests;

public class ShowroomConfigurationPhase1Tests
{
    private class DummyAuditLogService : IAuditLogService
    {
        public Task RecordAsync(
            string action,
            string module,
            string description,
            Guid? userId = null,
            string? userName = null,
            string? userRole = null,
            string? entityType = null,
            Guid? entityId = null,
            string? entityReference = null,
            string? oldValues = null,
            string? newValues = null,
            string? metadata = null,
            string outcome = "Success",
            CancellationToken cancellationToken = default) => Task.CompletedTask;

        public Task<PagedResult<AuditLogDto>> GetLogsAsync(
            AuditLogQueryParameters query,
            CancellationToken cancellationToken = default) =>
            Task.FromResult(new PagedResult<AuditLogDto>
            {
                Items = new List<AuditLogDto>(),
                TotalCount = 0,
                Page = query.Page,
                PageSize = query.PageSize
            });
    }

    private static AppDbContext CreateDb()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>()
            .UseInMemoryDatabase(Guid.NewGuid().ToString())
            .ConfigureWarnings(w => w.Ignore(InMemoryEventId.TransactionIgnoredWarning))
            .Options;
        return new AppDbContext(options);
    }

    private static ClaimsPrincipal CreatePrincipal(Guid userId, string role, bool isOwner)
    {
        var claims = new List<Claim>
        {
            new(ClaimTypes.NameIdentifier, userId.ToString()),
            new("sub", userId.ToString()),
            new(ClaimTypes.Name, "test_user"),
            new(ClaimTypes.Role, role),
            new("isOwner", isOwner ? "true" : "false")
        };
        return new ClaimsPrincipal(new ClaimsIdentity(claims, "TestAuth"));
    }

    private static void SetCaller(ControllerBase controller, Guid userId, string role, bool isOwner)
    {
        controller.ControllerContext = new ControllerContext
        {
            HttpContext = new DefaultHttpContext
            {
                User = CreatePrincipal(userId, role, isOwner)
            }
        };
    }

    // ── 1. OWNER VS MANAGER AUTHORIZATION FOR VEHICLE TYPES ───────────────────

    [Fact]
    public async Task Owner_CanCreateVehicleType_WithExplicitCode()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());
        var controller = new ShowroomVehicleTypesController(opsService);
        SetCaller(controller, Guid.NewGuid(), "Owner", true);

        var request = new CreateShowroomVehicleTypeRequest
        {
            Code = "LUXURY_SUV",
            Name = "Luxury SUV",
            DisplayOrder = 10,
            IsActive = true
        };

        var result = await controller.Create(request);
        var createdResult = Assert.IsType<CreatedAtActionResult>(result);
        var dto = Assert.IsType<ShowroomVehicleTypeDto>(createdResult.Value);
        Assert.Equal("LUXURY_SUV", dto.Code);
        Assert.Equal("Luxury SUV", dto.Name);
        Assert.True(dto.IsActive);
    }

    [Fact]
    public async Task Owner_CanCreateVehicleType_WithAutoGeneratedCode()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());
        var controller = new ShowroomVehicleTypesController(opsService);
        SetCaller(controller, Guid.NewGuid(), "Owner", true);

        var request = new CreateShowroomVehicleTypeRequest
        {
            Code = null, // No code provided by user
            Name = "Electric Hatchback",
            DisplayOrder = 11,
            IsActive = true
        };

        var result = await controller.Create(request);
        var createdResult = Assert.IsType<CreatedAtActionResult>(result);
        var dto = Assert.IsType<ShowroomVehicleTypeDto>(createdResult.Value);
        Assert.Equal("ELECTRIC_HATCHBACK", dto.Code);
        Assert.Equal("Electric Hatchback", dto.Name);
    }

    [Fact]
    public async Task Manager_CannotCreateVehicleType_Returns403Forbidden()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());
        var controller = new ShowroomVehicleTypesController(opsService);
        SetCaller(controller, Guid.NewGuid(), "Manager", false);

        var request = new CreateShowroomVehicleTypeRequest
        {
            Name = "Convertible",
            IsActive = true
        };

        var result = await controller.Create(request);
        var objResult = Assert.IsType<ObjectResult>(result);
        Assert.Equal(StatusCodes.Status403Forbidden, objResult.StatusCode);
    }

    [Fact]
    public async Task Staff_CannotCreateVehicleType_Returns403Forbidden()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());
        var controller = new ShowroomVehicleTypesController(opsService);
        SetCaller(controller, Guid.NewGuid(), "Staff", false);

        var request = new CreateShowroomVehicleTypeRequest
        {
            Name = "Station Wagon",
            IsActive = true
        };

        var result = await controller.Create(request);
        var objResult = Assert.IsType<ObjectResult>(result);
        Assert.Equal(StatusCodes.Status403Forbidden, objResult.StatusCode);
    }

    [Fact]
    public async Task Owner_CanUpdateVehicleType()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());
        var controller = new ShowroomVehicleTypesController(opsService);
        SetCaller(controller, Guid.NewGuid(), "Owner", true);

        var vt = new ShowroomVehicleType
        {
            Id = Guid.NewGuid(),
            Code = "MINI",
            Name = "Mini Car",
            DisplayOrder = 1,
            IsActive = true,
            CreatedAt = DateTime.UtcNow
        };
        await db.ShowroomVehicleTypes.AddAsync(vt);
        await db.SaveChangesAsync();

        var updateReq = new UpdateShowroomVehicleTypeRequest
        {
            Name = "Micro Car",
            DisplayOrder = 2
        };

        var result = await controller.Update(vt.Id, updateReq);
        var okResult = Assert.IsType<OkObjectResult>(result);
        var dto = Assert.IsType<ShowroomVehicleTypeDto>(okResult.Value);
        Assert.Equal("Micro Car", dto.Name);
        Assert.Equal(2, dto.DisplayOrder);
    }

    [Fact]
    public async Task Manager_CannotUpdateVehicleType_Returns403Forbidden()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());
        var controller = new ShowroomVehicleTypesController(opsService);
        SetCaller(controller, Guid.NewGuid(), "Manager", false);

        var vt = new ShowroomVehicleType
        {
            Id = Guid.NewGuid(),
            Code = "MINI",
            Name = "Mini Car",
            DisplayOrder = 1,
            IsActive = true,
            CreatedAt = DateTime.UtcNow
        };
        await db.ShowroomVehicleTypes.AddAsync(vt);
        await db.SaveChangesAsync();

        var result = await controller.Update(vt.Id, new UpdateShowroomVehicleTypeRequest { Name = "Updated" });
        var objResult = Assert.IsType<ObjectResult>(result);
        Assert.Equal(StatusCodes.Status403Forbidden, objResult.StatusCode);
    }

    [Fact]
    public async Task Owner_CanToggleVehicleTypeActive()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());
        var controller = new ShowroomVehicleTypesController(opsService);
        SetCaller(controller, Guid.NewGuid(), "Owner", true);

        var vt = new ShowroomVehicleType
        {
            Id = Guid.NewGuid(),
            Code = "VAN",
            Name = "Van",
            DisplayOrder = 5,
            IsActive = true,
            CreatedAt = DateTime.UtcNow
        };
        await db.ShowroomVehicleTypes.AddAsync(vt);
        await db.SaveChangesAsync();

        var result = await controller.ToggleActive(vt.Id);
        Assert.IsType<NoContentResult>(result);

        var reloaded = await db.ShowroomVehicleTypes.FindAsync(vt.Id);
        Assert.False(reloaded!.IsActive);
    }

    [Fact]
    public async Task Manager_CannotToggleVehicleTypeActive_Returns403Forbidden()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());
        var controller = new ShowroomVehicleTypesController(opsService);
        SetCaller(controller, Guid.NewGuid(), "Manager", false);

        var vt = new ShowroomVehicleType
        {
            Id = Guid.NewGuid(),
            Code = "VAN",
            Name = "Van",
            IsActive = true,
            CreatedAt = DateTime.UtcNow
        };
        await db.ShowroomVehicleTypes.AddAsync(vt);
        await db.SaveChangesAsync();

        var result = await controller.ToggleActive(vt.Id);
        var objResult = Assert.IsType<ObjectResult>(result);
        Assert.Equal(StatusCodes.Status403Forbidden, objResult.StatusCode);
    }

    // ── 2. OWNER VS MANAGER AUTHORIZATION FOR WORK TYPES ─────────────────────

    [Fact]
    public async Task Owner_CanCreateWorkType_WithAutoGeneratedCode()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());
        var controller = new ShowroomWorkTypesController(opsService);
        SetCaller(controller, Guid.NewGuid(), "Owner", true);

        var request = new CreateShowroomWorkTypeRequest
        {
            Name = "Engine Bay Detailing",
            Description = "Degrease and shine engine bay",
            DisplayOrder = 10,
            IsActive = true
        };

        var result = await controller.Create(request);
        var createdResult = Assert.IsType<CreatedAtActionResult>(result);
        var dto = Assert.IsType<ShowroomWorkTypeDto>(createdResult.Value);
        Assert.Equal("ENGINE_BAY_DETAILING", dto.Code);
        Assert.Equal("Engine Bay Detailing", dto.Name);
    }

    [Fact]
    public async Task Manager_CannotCreateWorkType_Returns403Forbidden()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());
        var controller = new ShowroomWorkTypesController(opsService);
        SetCaller(controller, Guid.NewGuid(), "Manager", false);

        var request = new CreateShowroomWorkTypeRequest
        {
            Name = "Headlight Restoration",
            IsActive = true
        };

        var result = await controller.Create(request);
        var objResult = Assert.IsType<ObjectResult>(result);
        Assert.Equal(StatusCodes.Status403Forbidden, objResult.StatusCode);
    }

    [Fact]
    public async Task Owner_CanUpdateWorkType()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());
        var controller = new ShowroomWorkTypesController(opsService);
        SetCaller(controller, Guid.NewGuid(), "Owner", true);

        var wt = new ShowroomWorkType
        {
            Id = Guid.NewGuid(),
            Code = "FOAM_WASH",
            Name = "Foam Wash",
            DisplayOrder = 1,
            IsActive = true,
            CreatedAt = DateTime.UtcNow
        };
        await db.ShowroomWorkTypes.AddAsync(wt);
        await db.SaveChangesAsync();

        var result = await controller.Update(wt.Id, new UpdateShowroomWorkTypeRequest { Name = "Snow Foam Wash" });
        var okResult = Assert.IsType<OkObjectResult>(result);
        var dto = Assert.IsType<ShowroomWorkTypeDto>(okResult.Value);
        Assert.Equal("Snow Foam Wash", dto.Name);
    }

    [Fact]
    public async Task Manager_CannotUpdateWorkType_Returns403Forbidden()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());
        var controller = new ShowroomWorkTypesController(opsService);
        SetCaller(controller, Guid.NewGuid(), "Manager", false);

        var wt = new ShowroomWorkType
        {
            Id = Guid.NewGuid(),
            Code = "FOAM_WASH",
            Name = "Foam Wash",
            IsActive = true,
            CreatedAt = DateTime.UtcNow
        };
        await db.ShowroomWorkTypes.AddAsync(wt);
        await db.SaveChangesAsync();

        var result = await controller.Update(wt.Id, new UpdateShowroomWorkTypeRequest { Name = "Snow Foam Wash" });
        var objResult = Assert.IsType<ObjectResult>(result);
        Assert.Equal(StatusCodes.Status403Forbidden, objResult.StatusCode);
    }

    [Fact]
    public async Task Owner_CanToggleWorkTypeActive()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());
        var controller = new ShowroomWorkTypesController(opsService);
        SetCaller(controller, Guid.NewGuid(), "Owner", true);

        var wt = new ShowroomWorkType
        {
            Id = Guid.NewGuid(),
            Code = "SPECIAL_WAX",
            Name = "Special Wax",
            IsActive = true,
            CreatedAt = DateTime.UtcNow
        };
        await db.ShowroomWorkTypes.AddAsync(wt);
        await db.SaveChangesAsync();

        var result = await controller.ToggleActive(wt.Id);
        Assert.IsType<NoContentResult>(result);

        var reloaded = await db.ShowroomWorkTypes.FindAsync(wt.Id);
        Assert.False(reloaded!.IsActive);
    }

    // ── 3. ACTIVE-ONLY VS HISTORICAL FILTERING ───────────────────────────────

    [Fact]
    public async Task GetAll_VehicleTypes_FilterActive_ReturnsActiveOnly()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());
        var controller = new ShowroomVehicleTypesController(opsService);
        SetCaller(controller, Guid.NewGuid(), "Manager", false);

        await db.ShowroomVehicleTypes.AddRangeAsync(
            new ShowroomVehicleType { Id = Guid.NewGuid(), Code = "SEDAN", Name = "Sedan", IsActive = true, CreatedAt = DateTime.UtcNow },
            new ShowroomVehicleType { Id = Guid.NewGuid(), Code = "BIKE", Name = "Bike", IsActive = false, CreatedAt = DateTime.UtcNow }
        );
        await db.SaveChangesAsync();

        var result = await controller.GetAll(isActive: true);
        var okResult = Assert.IsType<OkObjectResult>(result);
        var list = Assert.IsAssignableFrom<IEnumerable<ShowroomVehicleTypeDto>>(okResult.Value).ToList();

        Assert.Single(list);
        Assert.Equal("SEDAN", list[0].Code);
    }

    [Fact]
    public async Task GetAll_VehicleTypes_IncludeInactive_ReturnsAll()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());
        var controller = new ShowroomVehicleTypesController(opsService);
        SetCaller(controller, Guid.NewGuid(), "Owner", true);

        await db.ShowroomVehicleTypes.AddRangeAsync(
            new ShowroomVehicleType { Id = Guid.NewGuid(), Code = "SEDAN", Name = "Sedan", IsActive = true, CreatedAt = DateTime.UtcNow },
            new ShowroomVehicleType { Id = Guid.NewGuid(), Code = "BIKE", Name = "Bike", IsActive = false, CreatedAt = DateTime.UtcNow }
        );
        await db.SaveChangesAsync();

        var result = await controller.GetAll(includeInactive: true);
        var okResult = Assert.IsType<OkObjectResult>(result);
        var list = Assert.IsAssignableFrom<IEnumerable<ShowroomVehicleTypeDto>>(okResult.Value).ToList();

        Assert.Equal(2, list.Count);
    }

    // ── 4. "OTHER" WORK TYPE DESCRIPTION REQUIREMENTS ────────────────────────

    [Fact]
    public async Task CreateVehicleWork_WithOtherType_RequiresDescription()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());

        var showroom = new Showroom { Id = Guid.NewGuid(), MasterId = "SR1", Name = "Main", Address = "A", Phone = "9876543210", IsActive = true, CreatedAt = DateTime.UtcNow };
        var staff = new Staff { Id = Guid.NewGuid(), StaffMasterId = "ST1", Name = "Ravi", PhoneNumber = "9876543211", IsActive = true, CreatedAt = DateTime.UtcNow };
        var vt = new ShowroomVehicleType { Id = Guid.NewGuid(), Code = "SEDAN", Name = "Sedan", IsActive = true, CreatedAt = DateTime.UtcNow };
        var wtOther = new ShowroomWorkType { Id = Guid.NewGuid(), Code = "OTHER", Name = "Other", IsActive = true, IsOther = true, CreatedAt = DateTime.UtcNow };
        var date = DateTime.UtcNow.Date;

        await db.Showrooms.AddAsync(showroom);
        await db.Staff.AddAsync(staff);
        await db.ShowroomVehicleTypes.AddAsync(vt);
        await db.ShowroomWorkTypes.AddAsync(wtOther);
        await db.ShowroomStaffAssignments.AddAsync(new ShowroomStaffAssignment
        {
            Id = Guid.NewGuid(),
            ShowroomId = showroom.Id,
            StaffId = staff.Id,
            Date = date,
            CreatedAt = DateTime.UtcNow
        });
        await db.SaveChangesAsync();

        var reqWithoutNotes = new CreateShowroomVehicleWorkRequest
        {
            StaffId = staff.Id,
            VehicleTypeId = vt.Id,
            Date = date,
            ServiceItems = new List<CreateShowroomVehicleWorkItemRequest>
            {
                new() { WorkTypeId = wtOther.Id, Quantity = 1, Notes = null }
            }
        };

        var ex = await Assert.ThrowsAsync<ValidationException>(() => opsService.CreateVehicleWorkAsync(showroom.Id, reqWithoutNotes));
        Assert.Contains("Description of work performed is required", ex.Message);
    }

    [Fact]
    public async Task CreateVehicleWork_WithOtherType_PersistsDescriptionInNotes()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());

        var showroom = new Showroom { Id = Guid.NewGuid(), MasterId = "SR1", Name = "Main", Address = "A", Phone = "9876543210", IsActive = true, CreatedAt = DateTime.UtcNow };
        var staff = new Staff { Id = Guid.NewGuid(), StaffMasterId = "ST1", Name = "Ravi", PhoneNumber = "9876543211", IsActive = true, CreatedAt = DateTime.UtcNow };
        var vt = new ShowroomVehicleType { Id = Guid.NewGuid(), Code = "SEDAN", Name = "Sedan", IsActive = true, CreatedAt = DateTime.UtcNow };
        var wtOther = new ShowroomWorkType { Id = Guid.NewGuid(), Code = "OTHER", Name = "Other", IsActive = true, IsOther = true, CreatedAt = DateTime.UtcNow };
        var date = DateTime.UtcNow.Date;

        await db.Showrooms.AddAsync(showroom);
        await db.Staff.AddAsync(staff);
        await db.ShowroomVehicleTypes.AddAsync(vt);
        await db.ShowroomWorkTypes.AddAsync(wtOther);
        await db.ShowroomStaffAssignments.AddAsync(new ShowroomStaffAssignment
        {
            Id = Guid.NewGuid(),
            ShowroomId = showroom.Id,
            StaffId = staff.Id,
            Date = date,
            CreatedAt = DateTime.UtcNow
        });
        await db.SaveChangesAsync();

        var req = new CreateShowroomVehicleWorkRequest
        {
            StaffId = staff.Id,
            VehicleTypeId = vt.Id,
            Date = date,
            ServiceItems = new List<CreateShowroomVehicleWorkItemRequest>
            {
                new() { WorkTypeId = wtOther.Id, Quantity = 1, Notes = "Custom Scratch Removal" }
            }
        };

        var created = await opsService.CreateVehicleWorkAsync(showroom.Id, req);
        Assert.Single(created.ServiceItems);
        Assert.Equal("Custom Scratch Removal", created.ServiceItems[0].Notes);
        Assert.Equal("OTHER", created.ServiceItems[0].WorkTypeCode);
    }

    [Fact]
    public async Task CreateBatchVehicleWork_WithOtherType_PersistsDescriptionInNotes()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());

        var showroom = new Showroom { Id = Guid.NewGuid(), MasterId = "SR1", Name = "Main", Address = "A", Phone = "9876543210", IsActive = true, CreatedAt = DateTime.UtcNow };
        var staff = new Staff { Id = Guid.NewGuid(), StaffMasterId = "ST1", Name = "Ravi", PhoneNumber = "9876543211", IsActive = true, CreatedAt = DateTime.UtcNow };
        var vt = new ShowroomVehicleType { Id = Guid.NewGuid(), Code = "SEDAN", Name = "Sedan", IsActive = true, CreatedAt = DateTime.UtcNow };
        var wtOther = new ShowroomWorkType { Id = Guid.NewGuid(), Code = "OTHER", Name = "Other", IsActive = true, IsOther = true, CreatedAt = DateTime.UtcNow };
        var date = DateTime.UtcNow.Date;

        await db.Showrooms.AddAsync(showroom);
        await db.Staff.AddAsync(staff);
        await db.ShowroomVehicleTypes.AddAsync(vt);
        await db.ShowroomWorkTypes.AddAsync(wtOther);
        await db.ShowroomStaffAssignments.AddAsync(new ShowroomStaffAssignment
        {
            Id = Guid.NewGuid(),
            ShowroomId = showroom.Id,
            StaffId = staff.Id,
            Date = date,
            CreatedAt = DateTime.UtcNow
        });
        await db.SaveChangesAsync();

        var batchReq = new CreateBatchShowroomVehicleWorkRequest
        {
            StaffId = staff.Id,
            Date = date,
            Vehicles = new List<IndividualVehicleWorkEntry>
            {
                new()
                {
                    VehicleTypeId = vt.Id,
                    WorkTypeIds = new List<Guid> { wtOther.Id },
                    OtherDescription = "Alloy Wheel Polishing"
                }
            }
        };

        var createdList = await opsService.CreateBatchVehicleWorkAsync(showroom.Id, batchReq);
        Assert.Single(createdList);
        Assert.Equal("Alloy Wheel Polishing", createdList[0].ServiceItems[0].Notes);
    }

    // ── 5. HISTORICAL EDITING WITH INACTIVE TYPES ─────────────────────────────

    [Fact]
    public async Task UpdateVehicleWork_ExistingInactiveVehicleType_CanBePreserved()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());

        var showroom = new Showroom { Id = Guid.NewGuid(), MasterId = "SR1", Name = "Main", Address = "A", Phone = "9876543210", IsActive = true, CreatedAt = DateTime.UtcNow };
        var staff = new Staff { Id = Guid.NewGuid(), StaffMasterId = "ST1", Name = "Ravi", PhoneNumber = "9876543211", IsActive = true, CreatedAt = DateTime.UtcNow };
        var vtInactive = new ShowroomVehicleType { Id = Guid.NewGuid(), Code = "OLD_TYPE", Name = "Old Type", IsActive = false, CreatedAt = DateTime.UtcNow };
        var wtActive = new ShowroomWorkType { Id = Guid.NewGuid(), Code = "WASH", Name = "Wash", IsActive = true, CreatedAt = DateTime.UtcNow };
        var date = DateTime.UtcNow.Date;

        var existingWork = new ShowroomVehicleWork
        {
            Id = Guid.NewGuid(),
            ShowroomId = showroom.Id,
            StaffId = staff.Id,
            VehicleTypeId = vtInactive.Id,
            VehicleQuantity = 1,
            Date = date,
            Notes = "Old record notes",
            CreatedAt = DateTime.UtcNow
        };

        await db.Showrooms.AddAsync(showroom);
        await db.Staff.AddAsync(staff);
        await db.ShowroomVehicleTypes.AddAsync(vtInactive);
        await db.ShowroomWorkTypes.AddAsync(wtActive);
        await db.ShowroomStaffAssignments.AddAsync(new ShowroomStaffAssignment { Id = Guid.NewGuid(), ShowroomId = showroom.Id, StaffId = staff.Id, Date = date, CreatedAt = DateTime.UtcNow });
        await db.ShowroomVehicleWorks.AddAsync(existingWork);
        await db.SaveChangesAsync();

        // Updating notes while keeping the inactive vehicle type unchanged should NOT crash or throw
        var updateReq = new UpdateShowroomVehicleWorkRequest
        {
            VehicleTypeId = vtInactive.Id, // Unchanged
            Notes = "Updated notes"
        };

        var updated = await opsService.UpdateVehicleWorkAsync(showroom.Id, existingWork.Id, updateReq);
        Assert.NotNull(updated);
        Assert.Equal("Updated notes", updated!.Notes);
        Assert.Equal(vtInactive.Id, updated.VehicleTypeId);
    }

    [Fact]
    public async Task UpdateVehicleWork_ExistingInactiveWorkType_CanBePreserved()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());

        var showroom = new Showroom { Id = Guid.NewGuid(), MasterId = "SR1", Name = "Main", Address = "A", Phone = "9876543210", IsActive = true, CreatedAt = DateTime.UtcNow };
        var staff = new Staff { Id = Guid.NewGuid(), StaffMasterId = "ST1", Name = "Ravi", PhoneNumber = "9876543211", IsActive = true, CreatedAt = DateTime.UtcNow };
        var vtActive = new ShowroomVehicleType { Id = Guid.NewGuid(), Code = "SUV", Name = "SUV", IsActive = true, CreatedAt = DateTime.UtcNow };
        var wtInactive = new ShowroomWorkType { Id = Guid.NewGuid(), Code = "OLD_WORK", Name = "Old Work", IsActive = false, CreatedAt = DateTime.UtcNow };
        var date = DateTime.UtcNow.Date;

        var existingWork = new ShowroomVehicleWork
        {
            Id = Guid.NewGuid(),
            ShowroomId = showroom.Id,
            StaffId = staff.Id,
            VehicleTypeId = vtActive.Id,
            VehicleQuantity = 1,
            Date = date,
            CreatedAt = DateTime.UtcNow
        };
        var existingItem = new ShowroomVehicleWorkItem
        {
            Id = Guid.NewGuid(),
            ShowroomVehicleWorkId = existingWork.Id,
            WorkTypeId = wtInactive.Id,
            Quantity = 1,
            CreatedAt = DateTime.UtcNow
        };
        existingWork.ServiceItems.Add(existingItem);

        await db.Showrooms.AddAsync(showroom);
        await db.Staff.AddAsync(staff);
        await db.ShowroomVehicleTypes.AddAsync(vtActive);
        await db.ShowroomWorkTypes.AddAsync(wtInactive);
        await db.ShowroomStaffAssignments.AddAsync(new ShowroomStaffAssignment { Id = Guid.NewGuid(), ShowroomId = showroom.Id, StaffId = staff.Id, Date = date, CreatedAt = DateTime.UtcNow });
        await db.ShowroomVehicleWorks.AddAsync(existingWork);
        await db.SaveChangesAsync();

        // Updating notes and preserving existing inactive work type should succeed
        var updateReq = new UpdateShowroomVehicleWorkRequest
        {
            ServiceItems = new List<CreateShowroomVehicleWorkItemRequest>
            {
                new() { WorkTypeId = wtInactive.Id, Quantity = 1 }
            }
        };

        var updated = await opsService.UpdateVehicleWorkAsync(showroom.Id, existingWork.Id, updateReq);
        Assert.NotNull(updated);
        Assert.Single(updated!.ServiceItems);
        Assert.Equal(wtInactive.Id, updated.ServiceItems[0].WorkTypeId);
    }

    [Fact]
    public async Task UpdateVehicleWork_NewlyAddedInactiveWorkType_ThrowsValidationException()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());

        var showroom = new Showroom { Id = Guid.NewGuid(), MasterId = "SR1", Name = "Main", Address = "A", Phone = "9876543210", IsActive = true, CreatedAt = DateTime.UtcNow };
        var staff = new Staff { Id = Guid.NewGuid(), StaffMasterId = "ST1", Name = "Ravi", PhoneNumber = "9876543211", IsActive = true, CreatedAt = DateTime.UtcNow };
        var vtActive = new ShowroomVehicleType { Id = Guid.NewGuid(), Code = "SUV", Name = "SUV", IsActive = true, CreatedAt = DateTime.UtcNow };
        var wtActive = new ShowroomWorkType { Id = Guid.NewGuid(), Code = "WASH", Name = "Wash", IsActive = true, CreatedAt = DateTime.UtcNow };
        var wtInactive = new ShowroomWorkType { Id = Guid.NewGuid(), Code = "OLD_WORK", Name = "Old Work", IsActive = false, CreatedAt = DateTime.UtcNow };
        var date = DateTime.UtcNow.Date;

        var existingWork = new ShowroomVehicleWork
        {
            Id = Guid.NewGuid(),
            ShowroomId = showroom.Id,
            StaffId = staff.Id,
            VehicleTypeId = vtActive.Id,
            VehicleQuantity = 1,
            Date = date,
            CreatedAt = DateTime.UtcNow
        };
        existingWork.ServiceItems.Add(new ShowroomVehicleWorkItem
        {
            Id = Guid.NewGuid(),
            ShowroomVehicleWorkId = existingWork.Id,
            WorkTypeId = wtActive.Id,
            Quantity = 1,
            CreatedAt = DateTime.UtcNow
        });

        await db.Showrooms.AddAsync(showroom);
        await db.Staff.AddAsync(staff);
        await db.ShowroomVehicleTypes.AddAsync(vtActive);
        await db.ShowroomWorkTypes.AddRangeAsync(wtActive, wtInactive);
        await db.ShowroomStaffAssignments.AddAsync(new ShowroomStaffAssignment { Id = Guid.NewGuid(), ShowroomId = showroom.Id, StaffId = staff.Id, Date = date, CreatedAt = DateTime.UtcNow });
        await db.ShowroomVehicleWorks.AddAsync(existingWork);
        await db.SaveChangesAsync();

        // Attempting to newly add wtInactive to a work record that didn't have it must be rejected
        var updateReq = new UpdateShowroomVehicleWorkRequest
        {
            ServiceItems = new List<CreateShowroomVehicleWorkItemRequest>
            {
                new() { WorkTypeId = wtActive.Id, Quantity = 1 },
                new() { WorkTypeId = wtInactive.Id, Quantity = 1 }
            }
        };

        var ex = await Assert.ThrowsAsync<ValidationException>(() => opsService.UpdateVehicleWorkAsync(showroom.Id, existingWork.Id, updateReq));
        Assert.Contains("inactive and cannot be newly added", ex.Message);
    }

    [Fact]
    public async Task UpdateVehicleWork_RemoveInactiveWorkType_Succeeds()
    {
        var db = CreateDb();
        var opsService = new ShowroomOperationsService(db, new DummyAuditLogService());

        var showroom = new Showroom { Id = Guid.NewGuid(), MasterId = "SR1", Name = "Main", Address = "A", Phone = "9876543210", IsActive = true, CreatedAt = DateTime.UtcNow };
        var staff = new Staff { Id = Guid.NewGuid(), StaffMasterId = "ST1", Name = "Ravi", PhoneNumber = "9876543211", IsActive = true, CreatedAt = DateTime.UtcNow };
        var vtActive = new ShowroomVehicleType { Id = Guid.NewGuid(), Code = "SUV", Name = "SUV", IsActive = true, CreatedAt = DateTime.UtcNow };
        var wtActive = new ShowroomWorkType { Id = Guid.NewGuid(), Code = "WASH", Name = "Wash", IsActive = true, CreatedAt = DateTime.UtcNow };
        var wtInactive = new ShowroomWorkType { Id = Guid.NewGuid(), Code = "OLD_WORK", Name = "Old Work", IsActive = false, CreatedAt = DateTime.UtcNow };
        var date = DateTime.UtcNow.Date;

        var existingWork = new ShowroomVehicleWork
        {
            Id = Guid.NewGuid(),
            ShowroomId = showroom.Id,
            StaffId = staff.Id,
            VehicleTypeId = vtActive.Id,
            VehicleQuantity = 1,
            Date = date,
            CreatedAt = DateTime.UtcNow
        };
        existingWork.ServiceItems.Add(new ShowroomVehicleWorkItem
        {
            Id = Guid.NewGuid(),
            ShowroomVehicleWorkId = existingWork.Id,
            WorkTypeId = wtInactive.Id,
            Quantity = 1,
            CreatedAt = DateTime.UtcNow
        });

        await db.Showrooms.AddAsync(showroom);
        await db.Staff.AddAsync(staff);
        await db.ShowroomVehicleTypes.AddAsync(vtActive);
        await db.ShowroomWorkTypes.AddRangeAsync(wtActive, wtInactive);
        await db.ShowroomStaffAssignments.AddAsync(new ShowroomStaffAssignment { Id = Guid.NewGuid(), ShowroomId = showroom.Id, StaffId = staff.Id, Date = date, CreatedAt = DateTime.UtcNow });
        await db.ShowroomVehicleWorks.AddAsync(existingWork);
        await db.SaveChangesAsync();

        // Replacing wtInactive with wtActive (removing inactive type) succeeds
        var updateReq = new UpdateShowroomVehicleWorkRequest
        {
            ServiceItems = new List<CreateShowroomVehicleWorkItemRequest>
            {
                new() { WorkTypeId = wtActive.Id, Quantity = 1 }
            }
        };

        var updated = await opsService.UpdateVehicleWorkAsync(showroom.Id, existingWork.Id, updateReq);
        Assert.NotNull(updated);
        Assert.Single(updated!.ServiceItems);
        Assert.Equal(wtActive.Id, updated.ServiceItems[0].WorkTypeId);
    }
}
